name: bitacora_mantenimiento
description: Aplicación móvil para bitácora de mantenimiento vehicular
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  flutter_launcher_icons: ^0.14.4
  provider: ^6.1.1
  fl_chart: ^0.68.0
  pdf: ^3.10.7
  printing: ^5.11.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets - Imágenes y recursos
  assets:
    - assets/images/logos/
    - assets/images/icons/
    - assets/images/vehicles/
    - assets/images/maintenance/
    - assets/images/fondoapp/
  
  # Fuentes personalizadas
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/DroidSans-Bold.ttf
          weight: 700

# Configuración de íconos de la aplicación
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logos/icon_app.png"
  min_sdk_android: 21

